pipeline:
  name: flux.1-dev
  use_modelscope: true
  # ModelScope模型ID，例如：modelscope/flux.1-dev 或者具体的模型ID
  path: "MusePublic/FLUX.1-Kontext-Dev"  # 这里使用示例路径，实际使用时需要替换为真实的ModelScope模型ID
  # modelscope_cache_dir: "~/.cache/modelscope"  # 可选：指定ModelScope缓存目录
  dtype: torch.bfloat16
eval:
  num_steps: 20
  guidance_scale: 3.5
  protocol: fmeuler{num_steps}-g{guidance_scale}
quant:
  calib:
    batch_size: 16
  wgts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 16
      element_size: 512
      sample_size: -1
    low_rank:
      sample_batch_size: 16
      sample_size: -1
    skips: 
    - embed
    - resblock_shortcut
    - resblock_time_proj
    - transformer_proj_in
    - transformer_proj_out
    - down_sample
    - up_sample
  ipts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 16
      element_size: 512
      sample_size: -1
    skips: 
    - embed
    - resblock_shortcut
    - resblock_time_proj
    - transformer_proj_in
    - transformer_proj_out
    - transformer_norm
    - transformer_add_norm
    - down_sample
    - up_sample
  opts:
    calib_range:
      element_batch_size: 64
      sample_batch_size: 16
      element_size: 512
      sample_size: -1
  smooth:
    proj:
      element_batch_size: -1
      sample_batch_size: 16
      element_size: -1
      sample_size: -1
    attn:
      sample_batch_size: 16
      sample_size: -1